### ISSUE TITLE
URGENT: Rendre le bouton "Afficher le numéro" plus visible

### ISSUE THREAD

**Issue by pboko** [vteco/qpr#3]
Sur les pages des offres.Actuellement il est dans le bandeau, il faudrait voir comment le rajouter dans le texte

![image](https://cloud.githubusercontent.com/assets/1906061/6438588/eba90fe4-c0ca-11e4-96e2-920b56600fbb.png)

**Comment by lindavte** [comment]
svn revision ; 8314
